### ISSUE TITLE
PonyAPI endpoint has changed to use HTTPS

### ISSUE THREAD

**Issue by Xe** [ask-compu/CompuBot#2]
The code [here](https://github.com/ask-compu/CompuBot/blob/master/modules/episode.py#L31) needs to now point to https://ponyapi.apps.xeserv.us due to Xe/PonyAPI#6. It may continue working due to the redirect, but it is safer to update to use HTTPS natively.

**Comment by ask-compu** [comment]
alright fixing now

**Comment by ask-compu** [comment]
fixed in https://github.com/ask-compu/CompuBot/commit/4951486e064ba4bb079ee95c434d3f3af24303a0
